Repository rlawrenc/PrairieLearn-Ranked, pull requests merged in 2023-08, with the labels that each got.

#31 Profile Card: Display Name Population / Updating
  apps/prairielearn/src/pages/partials/plr/profileCard.ejs
  apps/prairielearn/src/pages/plrStudent/plrStudent.ejs
  apps/prairielearn/src/pages/plrStudent/plrStudent.js
  apps/prairielearn/src/pages/plrStudent/plrStudent.sql
  apps/prairielearn/src/pages/plrStudent/prohibitedWords.txt
  apps/prairielearn/src/server.js
Labels: frontend, backend

#32 Frontend Polish (ROUND 1)
  apps/prairielearn/assets/stylesheets/PLR.css
  apps/prairielearn/src/pages/partials/plr/allTimeScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/availableQuizzesList.ejs
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/seasonalScoreboard.ejs
  apps/prairielearn/src/pages/plrStaff/plrStaff.ejs
  apps/prairielearn/src/pages/plrStudent/plrStudent.ejs
Labels: frontend

#28 Achievements
  apps/prairielearn/src/admin_queries/PLR_1_start_sessions.json
  apps/prairielearn/src/admin_queries/PLR_1_start_sessions.sql
  apps/prairielearn/src/admin_queries/PLR_2.1_sim_live.json
  apps/prairielearn/src/admin_queries/PLR_2.1_sim_live.sql
  apps/prairielearn/src/admin_queries/PLR_2_sim_live.json
  apps/prairielearn/src/admin_queries/PLR_2_sim_live.sql
  apps/prairielearn/src/admin_queries/PLR_3_set_times.json
  apps/prairielearn/src/admin_queries/PLR_3_set_times.sql
  apps/prairielearn/src/admin_queries/PLR_4_end_live_session.json
  apps/prairielearn/src/admin_queries/PLR_4_end_live_session.sql
  apps/prairielearn/src/migrations/20230715221742_PLR_seasonal_session.sql
  apps/prairielearn/src/migrations/20230715221818_PLR_achievements.sql
  apps/prairielearn/src/migrations/20230716010045_PLR_trigger_insert_update_score_duration_and_rank.sql
  apps/prairielearn/src/migrations/20230723193045_PLR_trigger_seasonal_inserts.sql
  apps/prairielearn/src/migrations/20230723220648_PLR_trigger_notify.sql
  apps/prairielearn/src/migrations/20230730074300_PLR_Achievement_hat_trick_triggers.sql
  apps/prairielearn/src/migrations/20230730081901_PLR_Achievement_gotta_go_fast_triggers.sql
  apps/prairielearn/src/migrations/20230730092734_PLR_Achievement_placements_triggers.sql
  apps/prairielearn/src/migrations/20230801011024_PLR_Achievement_speed_demon_trigger.sql
  apps/prairielearn/src/migrations/20230801012036_PLR_Achievement_always_on_time_triggers.sql
  apps/prairielearn/src/migrations/20230801014818_PLR_Achievement_unstoppable_trigger.sql
  apps/prairielearn/src/server.js
  testCourse/courseInstances/Sp15/assessments/lv3-bonusPoints/infoAssessment.json
Labels: backend, integration, tests

#33 Create live assessment
  apps/prairielearn/src/migrations/20230723220648_PLR_trigger_notify.sql
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  testCourse/courseInstances/Sp15/assessments/Test_1/infoAssessment.json
  testCourse/questions/LVQ_1/info.json
  testCourse/questions/LVQ_1/question.html
  testCourse/questions/LVQ_1/server.py
Labels: frontend, backend, tests

#35 Create Simple Admin Queries
  apps/prairielearn/src/admin_queries/PLR_attach_achievement.json
  apps/prairielearn/src/admin_queries/PLR_attach_achievement.sql
  apps/prairielearn/src/admin_queries/PLR_end_live_session.json
  apps/prairielearn/src/admin_queries/PLR_end_live_session.sql
  apps/prairielearn/src/admin_queries/PLR_insert_&_enroll_user.json
  apps/prairielearn/src/admin_queries/PLR_insert_&_enroll_user.sql
  apps/prairielearn/src/admin_queries/PLR_insert_assessment.json
  apps/prairielearn/src/admin_queries/PLR_insert_assessment.sql
  apps/prairielearn/src/admin_queries/PLR_insert_assessment_instance.json
  apps/prairielearn/src/admin_queries/PLR_insert_assessment_instance.sql
  apps/prairielearn/src/admin_queries/PLR_insert_duration.json
  apps/prairielearn/src/admin_queries/PLR_insert_duration.sql
  apps/prairielearn/src/admin_queries/PLR_update_score.json
  apps/prairielearn/src/admin_queries/PLR_update_score.sql
Labels: frontend, integration

#36 Fixing the bug with the "time.seconds" call.
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
Labels: bug

#37 Achievement Population
  apps/prairielearn/src/migrations/20230715221818_PLR_achievements.sql
  apps/prairielearn/src/pages/partials/plr/allTimeScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/plrScoreboard.sql
  apps/prairielearn/src/pages/partials/plr/seasonalScoreboard.ejs
Labels: frontend, backend, integration

#38 Achievements on Profile Card
  apps/prairielearn/src/pages/partials/plr/achievementList.ejs
  apps/prairielearn/src/pages/partials/plr/allTimeScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/profileCard.ejs
  apps/prairielearn/src/pages/partials/plr/seasonalScoreboard.ejs
Labels: frontend, backend

#42 Test Fixes: Linters
  .github/workflows/main.yml
Labels: integration, tests

#43 Bug Fixes: Tables & Ordering
  apps/prairielearn/src/migrations/20230715221603_PLR_students.sql
  apps/prairielearn/src/migrations/20230729074712_PLR_enrollment.sql
  apps/prairielearn/src/pages/partials/plr/plrScoreboard.sql
Labels: bug, backend

#44 Bug fix enrollment
  apps/prairielearn/src/migrations/20230729074712_PLR_enrollment.sql
Labels: bug, backend

#34 Scoreboard Highlights + Testing Workflow
  .github/workflows/cla.yml
  apps/prairielearn/assets/stylesheets/PLR.css
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/plrScoreboard.sql
Labels: frontend

#46 Added Database Documentation
  docs/PLR/database/PLR_Database_Documentation.md
  docs/PLR/database/PLR_ER_Diagram.PNG
Labels: documentation

#47 Change multiplier
  apps/prairielearn/src/migrations/20230716010045_PLR_trigger_insert_update_score_duration_and_rank.sql
Labels: backend

#50 DockerHub Push Test
  .github/workflows/main.yml
Labels: integration, tests

#51 Pushing to Dockerhub with Latest
  .github/workflows/images.yml
Labels: integration, tests

#52 DockerHub drlawrenc changes
  .github/workflows/images.yml
  .github/workflows/main.yml
  apps/prairielearn-ranked/run-plr.sh
Labels: integration

#53 Update aot
  apps/prairielearn/src/admin_queries/PLR_fill_and_enroll_users.json
  apps/prairielearn/src/admin_queries/PLR_fill_and_enroll_users.sql
  apps/prairielearn/src/admin_queries/PLR_fill_live_assessments.json
  apps/prairielearn/src/admin_queries/PLR_fill_live_assessments.sql
  apps/prairielearn/src/migrations/20230715221603_PLR_students.sql
  apps/prairielearn/src/migrations/20230801012036_PLR_Achievement_always_on_time_triggers.sql
Labels: bug, backend, integration

#54 Fix number formatting
  apps/prairielearn/src/pages/partials/plr/allTimeScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/seasonalScoreboard.ejs
Labels: bug, frontend

#55 Fix No Results Bug
  apps/prairielearn/src/pages/partials/plr/allTimeScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/seasonalScoreboard.ejs
Labels: bug, frontend

#56 Move Inserts into self contained Migration
  apps/prairielearn/src/migrations/20230715221818_PLR_achievements.sql
  apps/prairielearn/src/migrations/20230729074712_PLR_enrollment.sql
  apps/prairielearn/src/migrations/20230801012036_PLR_Achievement_always_on_time_triggers.sql
  apps/prairielearn/src/migrations/20230812180255_PLR_inserts.sql
Labels: backend

#57 Fix Display
  apps/prairielearn/src/pages/partials/plr/allTimeScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/plrScoreboard.sql
  apps/prairielearn/src/pages/partials/plr/profileCard.ejs
  apps/prairielearn/src/pages/partials/plr/seasonalScoreboard.ejs
Labels: bug, frontend

#58 Decimals and documentation
  apps/prairielearn/src/admin_queries/PLR_1_start_sessions.sql
  apps/prairielearn/src/admin_queries/PLR_fill_and_enroll_users.sql
  apps/prairielearn/src/pages/partials/plr/allTimeScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/seasonalScoreboard.ejs
Labels: bug, documentation, frontend, backend, integration

#59 Move docs
  docs/PLR/database_walkthrough/PLR_Database_Documentation.md
  docs/PLR/database_walkthrough/PLR_ER_Diagram.PNG
  docs/PLR/deployment_walkthrough/deployment_walkthrough.md
  docs/PLR/development_walkthrough/prairielearn_development_guidance.md
  docs/PLR/drone_walkthrough/drone_setup.md
  docs/PLR/frontend_and_routing/Frontend_and_Routing.md
  docs/PLR/frontend_and_routing/images/staff_page_fullscreen_view.png
  docs/PLR/frontend_and_routing/images/staff_page_quiz_view.png
  docs/PLR/frontend_and_routing/images/student_view_achievments.png
  docs/PLR/frontend_and_routing/images/student_view_display_name.png
  docs/PLR/server_routing_async/PLR_server_routing_async_documentation.md
  docs/PLR/staff_walkthrough/staff_walkthrough.md
  docs/PLR/staff_walkthrough/staff_walkthrough_Images/PLRStaff.PNG
  docs/PLR/updated_files_walkthrough/added_and_updated_files.md
Labels: documentation
