Repository rlawrenc/PrairieLearn-Ranked, pull requests merged in 2023-07, with the labels that each got.

#4 Create Seasonal transfer trigger
  apps/prairielearn/src/migrations/20230715221603_PLR_students.sql
  apps/prairielearn/src/migrations/20230715221659_PLR_live_session.sql
  apps/prairielearn/src/migrations/20230715221742_PLR_seasonal_session.sql
  apps/prairielearn/src/migrations/20230723193045_PLR_trigger_seasonal_inserts.sql
Labels: backend, integration

#5 Admin Queries
  apps/prairielearn/src/admin_queries/PLR_students.json
  apps/prairielearn/src/admin_queries/PLR_students.sql
  apps/prairielearn/src/admin_queries/Users.json
  apps/prairielearn/src/admin_queries/Users.sql
Labels: frontend, backend

#6 Staff model rework
  apps/prairielearn/src/migrations/20230715221603_PLR_students.sql
  apps/prairielearn/src/migrations/20230716010045_PLR_trigger_insert_update_score_duration_and_rank.sql
  apps/prairielearn/src/pages/plrStaff/plrStaff.js
Labels: bug, backend

#7 Admin Queries: LIVE
  apps/prairielearn/src/admin_queries/PLR_end.json
  apps/prairielearn/src/admin_queries/PLR_end.sql
  apps/prairielearn/src/admin_queries/PLR_start.json
  apps/prairielearn/src/admin_queries/PLR_start.sql
  apps/prairielearn/src/admin_queries/PLR_start_double.json
  apps/prairielearn/src/admin_queries/PLR_start_double.sql
  apps/prairielearn/src/admin_queries/PLR_students.json
  apps/prairielearn/src/admin_queries/PLR_students.sql
  apps/prairielearn/src/admin_queries/Users.json
  apps/prairielearn/src/admin_queries/Users.sql
  apps/prairielearn/src/migrations/20230715221603_PLR_students.sql
Labels: backend

#10 Added Notify Trigger
  apps/prairielearn/src/migrations/20230723220648_PLR_trigger_notify.sql
Labels: backend

#11 Server.js and SSE Client Info
  apps/prairielearn/src/server.js
  apps/prairielearn/src/sseClients.js
Labels: backend

#12 SSE Client Edits
  apps/prairielearn/src/sseClients.js
Labels: backend

#13 plrStudent SSE Connections
  apps/prairielearn/src/pages/plrStudent/plrStudent.ejs
  apps/prairielearn/src/pages/plrStudent/plrStudent.js
  apps/prairielearn/src/pages/plrStudent/plrStudent.sql
  apps/prairielearn/src/pages/plrStudent/plrStudentModel.js
Labels: frontend, backend

#14 BUG: Get Live Results
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/plrStudent/plrStudent.js
  apps/prairielearn/src/pages/plrStudent/plrStudent.sql
  apps/prairielearn/src/pages/plrStudent/plrStudentModel.js
Labels: bug, frontend, backend

#15 Fix Live Scoreboard Load
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/plrStudent/plrStudent.js
Labels: bug, frontend

#17 refactor code by changing callbacks to promises for a clean solution
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/plrStudent/plrStudent.js
Labels: backend

#19 Create plr enrollment
  apps/prairielearn/src/admin_queries/PLR_start.json
  apps/prairielearn/src/admin_queries/PLR_start.sql
  apps/prairielearn/src/migrations/20230715221603_PLR_students.sql
  apps/prairielearn/src/migrations/20230729074712_PLR_enrollment.sql
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/plrStudent/plrStudent.js
  apps/prairielearn/src/pages/plrStudent/plrStudent.sql
  apps/prairielearn/src/pages/plrStudent/plrStudentModel.js
  apps/prairielearn/src/server.js
Labels: bug, frontend, backend, integration

#20 Plr student model rework
  apps/prairielearn/src/pages/partials/plr/plrScoreboard.sql
  apps/prairielearn/src/pages/partials/plr/plrScoreboardModel.js
  apps/prairielearn/src/pages/plrStudent/plrStudent.js
  apps/prairielearn/src/server.js
Labels: backend

#21 Seasonal Scoreboard Trigger Fix
  apps/prairielearn/src/migrations/20230723193045_PLR_trigger_seasonal_inserts.sql
Labels: bug, backend

#22 PLR Staff Created with Student Equivalent
  apps/prairielearn/src/pages/plrStaff/plrStaff.js
  apps/prairielearn/src/pages/plrStudent/plrStudent.ejs
Labels: frontend, backend, integration

#23 Available Quizzes List Population
  apps/prairielearn/src/pages/partials/plr/availableQuizzesList.ejs
  apps/prairielearn/src/pages/plrStaff/plrStaff.ejs
  apps/prairielearn/src/pages/plrStaff/plrStaff.js
  apps/prairielearn/src/pages/plrStaff/plrStaff.sql
Labels: frontend, backend

#24 Create student total score trigger
  apps/prairielearn/src/migrations/20230715221603_PLR_students.sql
  apps/prairielearn/src/migrations/20230715221659_PLR_live_session.sql
  apps/prairielearn/src/migrations/20230715221742_PLR_seasonal_session.sql
  apps/prairielearn/src/migrations/20230715221818_PLR_achievements.sql
  apps/prairielearn/src/migrations/20230716010045_PLR_trigger_insert_update_score_duration_and_rank.sql
  apps/prairielearn/src/migrations/20230723220648_PLR_trigger_notify.sql
  apps/prairielearn/src/migrations/20230729074712_PLR_enrollment.sql
  apps/prairielearn/src/migrations/20230729210129_PLR_total_score_trigger.sql
Labels: backend

#25 Update Admin Queries
  apps/prairielearn/src/admin_queries/PLR_end.json
  apps/prairielearn/src/admin_queries/PLR_end_live_session.json
  apps/prairielearn/src/admin_queries/PLR_end_live_session.sql
  apps/prairielearn/src/admin_queries/PLR_start.json
  apps/prairielearn/src/admin_queries/PLR_start.sql
  apps/prairielearn/src/admin_queries/PLR_start_double.json
  apps/prairielearn/src/admin_queries/PLR_start_double.sql
  apps/prairielearn/src/admin_queries/PLR_start_live_session.json
  apps/prairielearn/src/admin_queries/PLR_start_live_session.sql
Labels: integration

#26 Create all time scoreboard
  apps/prairielearn/src/migrations/20230715221742_PLR_seasonal_session.sql
  apps/prairielearn/src/migrations/20230723193045_PLR_trigger_seasonal_inserts.sql
  apps/prairielearn/src/pages/partials/plr/allTimeScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/plrScoreboard.sql
  apps/prairielearn/src/pages/partials/plr/plrScoreboardModel.js
  apps/prairielearn/src/pages/plrStaff/plrStaff.js
  apps/prairielearn/src/pages/plrStudent/plrStudent.js
  apps/prairielearn/src/server.js
Labels: frontend, backend

#27 Fix Duration & Scoreboard Clearing
  apps/prairielearn/src/migrations/20230715221659_PLR_live_session.sql
  apps/prairielearn/src/migrations/20230716010045_PLR_trigger_insert_update_score_duration_and_rank.sql
  apps/prairielearn/src/pages/partials/navbarInstructor.ejs
  apps/prairielearn/src/pages/partials/navbarStudent.ejs
  apps/prairielearn/src/pages/partials/plr/liveScoreboard.ejs
  apps/prairielearn/src/pages/partials/plr/plrScoreboard.sql
Labels: bug, frontend, backend

#29 When Quiz Clicked: is_live = TRUE
  apps/prairielearn/src/pages/partials/plr/availableQuizzesList.ejs
  apps/prairielearn/src/pages/plrStaff/plrStaff.js
  apps/prairielearn/src/pages/plrStaff/plrStaff.sql
Labels: frontend, backend, integration

#30 Disabling of quizzes, and FALSE flag
  apps/prairielearn/src/migrations/20230715221659_PLR_live_session.sql
  apps/prairielearn/src/pages/partials/plr/availableQuizzesList.ejs
  apps/prairielearn/src/pages/plrStaff/plrStaff.sql
Labels: frontend, backend, integration
